### ISSUE TITLE
Patient - create and add the HumanName profile with the middleName extension

### ISSUE THREAD

**Issue by VikJer** [HL7Sweden/basprofiler-r4#1]
Create the middleName extension (or simply reuse the Norwegian one once they've updated the use description and turned it Nordic)

Create a profile of the HumanName datatype

Bind the Patient.name to the profiled HumanName

**Comment by HL7Sverige** [comment]
Klart, se http://build.fhir.org/ig/danka74/basprofiler-r4/StructureDefinition-SEBasisHumanName.html
