### ISSUE TITLE
Mappings?

### ISSUE THREAD

**Issue by danka74** [HL7Sweden/basprofiler-r4#12]
Hej,
hur stor är aptiten för att lägga till mappings till profilerna? Ex. mappning till NI, NIM:ar eller existerande tjänstekontrakt? Det finns  olika nivåer man kan mappa på, från informella till användning av FHIR Mapping Language.

**Comment by VikJer** [comment]
Deltagarna får i uppgift att fundera på konkreta exempel då en mappning (på någon nivå) kan vara användbart. 

Om vi inte lyckas komma på konkreta behov så stänger vi ärendet efter årsskiftet.

**Comment by HL7Sverige** [comment]
Vi stänger detta ärende men tar upp frågan igen om behovet uppstår av mappningar

**Comment by HL7Sverige** [comment]
Se förra kommentaren
