### ISSUE TITLE
Practitioner - Qualification

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#13]
Kristofer - ta fram förslag på kodverk för legitimerade yrkeskoder och hur det ska refereras
Emmeli - Beskriv hur förskrivningsrätt uttryckt i NLL

**Comment by danka74** [comment]
Kodverk finns i massor. SoS och SKR har tagit fram ett förslag till kodverk för yrken/etc. https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct/45991000052106?fhir_vs=refset/68581000052104&includeDesignations=true

**Comment by HL7Sverige** [comment]
Att göra:
Förskrivarkod och gruppförskrivarkod läggs under Practitioner under qualifier
Skapa kodsystem för typ av kod (Förskrivarkod/gruppförskrivarkod)
Föreslå identifier.system (se över vad som finns kopplat till HOSP, OID finns hos SoS)

**Comment by danka74** [comment]
https://informationsstruktur.socialstyrelsen.se/NIM-H%C3%A4lso-och-sjukv%C3%A5rdspersonal

**Comment by danka74** [comment]
NIM:en för Hos-personal innehåller attributen befattning, legitimation och specialistkompetens

**Comment by danka74** [comment]
Lite förtydligande: är detta för de legitimerade yrkena enbart, dvs. enbart ex. SSK och inte barnmorska (även om en barnmorska (i Sverige) alltid är en SSK), leg.läk och inte ST-läk i geriatrik (även om en ST-läk i geriatrik också alltid är leg.läk)? Och hur gör vi med särskilda förordnanden? Ligger de på PractitionerRole?

**Comment by danka74** [comment]
Har lagt till 

- HOSP https://www.socialstyrelsen.se/statistik-och-data/register/alla-register/halso--och-sjukvardspersonal/
- SOSNYK https://www.socialstyrelsen.se/utveckla-verksamhet/e-halsa/klassificering-och-koder/andra-kodverk/sosnyk/
- SKR (Snomed CT-urval)

Behöver diskutera var (Practitioner/PractitionerRole) samt hur (explicit eller implicit).

**Comment by HL7Sverige** [comment]
HOSP läggs in under practitioner 0..1
SOSNYK läggs in under practitioner och practitionerRole 0..1
SKR läggs in under practitioner och practitionerRole 0..1
