### ISSUE TITLE
Läs på Practitioner och PractitionerRole och gör en sammanställning över hur de är tänkta att användas

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#14]
Tobias och Lars gör detta till nästa möte

**Comment by tobiasblom** [comment]
Möte Lars och Tobias 21/1:

Practitioner syftar till en individ som har ett officiellt uppdrag i hälso- och sjukvården. Den bör således innehålla **Legitimerad yrkestitel** och **Individuell förskrivarkod**. Eventuellt även specialistkompetens samt liknande. _Vi behöver skapa en extension för Individuell förskrivarkod._

PractitionerRole beskriver en roll som bör vara kopplad till själva anställningen. Den kan innehålla **rättigheter** som är knutna till en enhet och **gruppförskrivarkod**. PractitionerRole kan också innehålla yrkestitel men då i sammanhanget med att en person är anställd i egenskap av en yrkesroll.

**Comment by danka74** [comment]
Är förskrivarkod en identifierare? https://vemfargoravad.socialstyrelsen.se/sida/koder-att-forskriva-lakemedel-och-hjalpmedel
Inte säker hur man gör för icke-legitimerade läkare.

**Comment by tobiasblom** [comment]
Förskrivarkod är så vitt jag förstått en identifierare. Det är en personlig kod som följer med under hela yrkeslivet oavsett arbetsplats. Icke legitimerade läkare har ingen förskrivarkod under Practitioner utan den återfinns istället under PractitionerRole som beskriver deras roll/anställning som AT-läkare (t.ex.).

Huruvida man ska ha en redundant förskrivarkod för alla under PractitionerRole har jag ingen tanke om. Jag undrar dock vad den skulle tillföra. Jag känner mig dock lite osäker för att kunna uttala mig.

**Comment by HL7Sverige** [comment]
Att göra: 
Förskrivarkod och gruppförskrivarkod läggs under Practitioner under qualifier
Skapa kodsystem för typ av kod (Förskrivarkod/gruppförskrivarkod)
Föreslå identifier.system (se över vad som finns kopplat till HOSP, OID finns hos SoS)

**Comment by HL7Sverige** [comment]
Lägg legitimerad yrkeskod och befattningskod (sic!) kopplat till Practitioner.qualifier

**Comment by HL7Sverige** [comment]
> Att göra:
> Förskrivarkod och gruppförskrivarkod läggs under Practitioner under qualifier
> Skapa kodsystem för typ av kod (Förskrivarkod/gruppförskrivarkod)
> Föreslå identifier.system (se över vad som finns kopplat till HOSP, OID finns hos SoS)

Detta är klart. Återstår legitimerad yrkeskod och befattningskod

**Comment by HL7Sverige** [comment]
Stänger ärendet då legitimerad yrkeskod hanteras i #13  och befattningskod i #20
