### ISSUE TITLE
PractitionerRole - code

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#19]
SKRs kodverk för yrkeskoder - ej färdigt, men kan tas med i exempel
SoSNyk - etablerat kodverk som kan läggas in i profilen
HSA  befattningskoder - etablerat kodverk som kan läggas in i profilen

**Comment by danka74** [comment]
Observera att vissa av dessa koder är mer lämpade för Practitioner.qualification

**Comment by danka74** [comment]
https://informationsstruktur.socialstyrelsen.se/NIM-H%C3%A4lso-och-sjukv%C3%A5rdspersonal

**Comment by HL7Sverige** [comment]
@larbo4  - förslag på hur HSA befattningskoder ska läggas in i profilen

**Comment by HL7Sverige** [comment]
fortfarande utestående frågan angående befattningskoder

**Comment by HL7Sverige** [comment]
Påminn Lars om detta

**Comment by larbo4** [comment]
HSA:s befattningskodverk är, som de festa andra som har gjorts i ämnet, inte helt renodlat. De blandar yrkeskategorier med befattning. I kodverket finns ex legitimerad ”läkare legitimerad, annan” som borde klassas som yrkeskategori. Sedan finns specialistläkare som kan vara en befattning men i kodverket så har de inte specat viken sorts specialistläkare. Det finns däremot i SOSNYK men även i det kodverket blandas yrke med befattning. Jag tror att en måste göra ett urval från kodverken för att få det mer renodlat. Alla koderna både i befattningskodverket och i SOSNYK har en snomed-kod så det borde gå att göra ett refset från snomed med endast befattningar. Men det har ju visat sig svårigheten att särskilja dessa två grupper åt, yrkeskategori och befattning, så det återstår att se hur och om det går.

**Comment by HL7Sverige** [comment]
Frågan som återstår är om HSA befattningskod (som är ett välanvänt kodverk och bör ha representation i basprofilerna) ska skickas som en practitioner.qualification eller en practitionerRole.code. Enligt Lars svar ovan så kan det tolkas som både och.
Fråga till HSA förvaltningen: 
Används HSA befattningskod framför allt för att beskriva egenskaper kopplade till individer som har ett officiellt uppdrag i hälso- och sjukvården eller för rollen som är kopplad till själva anställningen?
@larbo4 tar med frågan till HSA.

**Comment by HL7Sverige** [comment]
Svar från HSA:
När det gäller din fråga om hur Befattning används så kan det vara kopplat både till individers uppdrag inom hälso- och sjukvård och individers anställning. Tjänsten Pascal använder bl.a. befattning som behörighetsgrundande information där de har pekat ut att vissa befattningskoder i kombination med legitimerad yrkesgrupp och förskrivarkod från HSA ger en viss administratörsroll.

**Comment by HL7Sverige** [comment]
Koppla HSA-befattning till både qualification och practitionerRole.code på samma sätt som för sosnyk och skr-yrkeskod
@larbo4  uppdaterar med OID
