### ISSUE TITLE
Patient - enable the use of Swedish ID types in Patient.identifier

### ISSUE THREAD

**Issue by VikJer** [HL7Sweden/basprofiler-r4#2]
Slice the Patient.identifier using the Patient.identifier.system as the discriminator.

Add one slice for each of the following types:

- Personnummer (1.2.752.129.2.1.3.1)
- Samordningsnummer (1.2.752.129.2.1.3.3)
- Nationellt reservnummer (OID saknas?)

(Lokalt reservnummer?)

**Comment by HL7Sverige** [comment]
LMA nummer - behov att ha med som slice samt med en nationell ID typ
Ska vi göra identifierare obligatorisk? Finns användningsfall där man inte skickar med identifierare

**Comment by HL7Sverige** [comment]
Har kontaktat migrationsverket med frågan om LMA nummer. Har fått svar att dom planerar för en uppslagstjänst för att kunna verifiera giltighet av LMA nummer men inget svar angående att tillhandahålla beständig länk för LMA nummer

Frågan är om detta är en tillräckligt stor del av tänkte användningsfall för att ta med i FHIR basprofil eller om man får hantera detta själv genom egen definierad slice

**Comment by HL7Sverige** [comment]
slice på identifierare klar - http://build.fhir.org/ig/danka74/basprofiler-r4/StructureDefinition-SEPatient.html

**Comment by HL7Sverige** [comment]
Ta fram en Profil på Identifier för LMA nummer och publicera i paketet grundprofiler

**Comment by VikJer** [comment]
Ärendet följs upp på nästa möte.

**Comment by HL7Sverige** [comment]
LMA profil framtagen, ärendet stängs
