### ISSUE TITLE
Patient - MaritalStatus

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#28]
Utred hur vi kan representera Skatteverkets koder för civilstånd genom utökning eller conceptMap

**Comment by annarossander** [comment]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/annro60/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel="themeData" href="file:///C:/Users/annro60/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/annro60/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>






<div align="center">


FHIR internationella | Skatteverket | NI
-- | -- | --
A Annulled | &nbsp; | &nbsp;
D Divorced | S Skild |  20295000 \| skild \|
I Interlocutory | &nbsp; | &nbsp;
L Legally Separated | &nbsp; | &nbsp;
M Married | G Gift | 87915002 \| gift \|
P Polygamous | &nbsp; | &nbsp;
S Never Married | &nbsp; | &nbsp;
T Domestic partner |  | &nbsp;
U unmarried | OG Ogift | 59961000052103 \| ogift \| (SE)
W Widowed | Ä Änka/änkling | 33553000 \| änka/änkling \|
&nbsp; | EP Efterlevande partner | &nbsp;
&nbsp; | RP Registrerad partner | &nbsp;
&nbsp; | SP Skild partner | &nbsp;
UNK unknown | &nbsp;| &nbsp;



</div>

**Comment by HL7Sverige** [comment]
Har lagt till ett förslag där officiellt kodsystem kombineras med urval ur SKV för att täcka in ovanstående koder

**Comment by o-medin** [comment]
I rubriken är "i" och "t" omkastade i "Marital". ("Martial" betyder "krigisk", dvs i idealfallet motsatsen till "äktenskaplig".)

**Comment by danka74** [comment]
Behov av ConceptMap mellan Navet och FHIR och Snomed CT.

**Comment by HL7Sverige** [comment]
Beslut att inte ta fram concept map nu utan om behov uppstår och kommuniceras. 
Uppdatera IG med översättningstabell

**Comment by HL7Sverige** [comment]
Fixed
