### ISSUE TITLE
Organization - identifier

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#29]
Skapa slices på identifier för:
HSA-ID
Organisationsnummer

**Comment by HL7Sverige** [comment]
@larbo4 
Oklarheter råder om vilken OID som ska användas för:
HSA-ID för person
HSA-ID för organisation

Kan du återkoppla om detta?

**Comment by larbo4** [comment]
Det finns inga olika OID:ar för person eller organisation. Det som har gjort det oklart är att det finns OID:ar som går mot objektklasserna i HSA och de är för person eller organisation men OID:en är för hela klassen inte för attributet 
objektklasser
· EmployeeHsaId urn:oid:1.2.752.29.6.2.1
· ComissionHsaId urn:oid:1.2.752.29.6.12.1
· healthCareUnitHsaId urn:oid:1.2.752.29.6.13.1
· healthCareProviderHsaId urn:oid:1.2.752.29.6.10.1
Det som är lite olyckligt är att det finns två OID:er för attributet HSA-id. Ett gammalt från CeHis-tiden (1.2.752.129.2.1.4.1) och ett nyare som gjorts på HSA (1.2.752.29.4.19). Det som jag tror har använts mest är det gamla id:et
