### ISSUE TITLE
Organization - type

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#30]
Finns behov av att kunna uttrycka:
HSA verksamhetskoder (Arvid)
SoS verksamhetsområde (Rikard)
IVO verksamhetskoder (Rikard)

Utred om det finns OID eller motsvarande för dessa som vi kan använda

**Comment by HL7Sverige** [comment]
Dokumentation över kodsystemen
[MVO_koder_senaste_från SoS-webben_Verksamhetskodslista2006.pdf](https://github.com/HL7Sweden/basprofiler-r4/files/6598442/MVO_koder_senaste_fran.SoS-webben_Verksamhetskodslista2006.pdf)
[hsa_innehall_verksamhetskod_version_5.12_2020-10-22.pdf](https://github.com/HL7Sweden/basprofiler-r4/files/6598443/hsa_innehall_verksamhetskod_version_5.12_2020-10-22.pdf)
[IVO verksamhetskoder.txt](https://github.com/HL7Sweden/basprofiler-r4/files/6598444/IVO.verksamhetskoder.txt)

**Comment by HL7Sverige** [comment]
OID för HSA verksamhetskoder: 1.2.752.129.2.2.1.3

**Comment by HL7Sverige** [comment]
@danka74 kollar upp SoS verksamhetskodlista och om den går att representera med OID eller URI
@HL7Sverige lägger upp HSA verksamhetskod enligt förslag
@VikJer kontaktar IVO

**Comment by danka74** [comment]
SoS: https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/sjukhuskoder-kodlista-verksamhetsomraden-2006.pdf

IVO har en lista för verksamheter oxå: https://www.ivo.se/globalassets/dokument/publicerat/blanketter/anmalan-av-verksamhet-enligt-patientsakerhetslagen-2010659-psl/anmalan-av-verksamhet-enligt-patientsakerhetslagen-210618.pdf

Inga OID:ar ännu men jag frågar runt.

**Comment by HL7Sverige** [comment]
@HL7Sverige ping
ping @danka74  - kommer vi att få fram OID:ar för IVO verksamhetskod och SoS Verksamhetskod?

**Comment by danka74** [comment]
Inga OID:ar från SoS för verksamhetskoder.

**Comment by danka74** [comment]
IVO har heller ingen OID för sina verksamhetskoder.

**Comment by danka74** [comment]
Sorry, stängde av misstag.

**Comment by HL7Sverige** [comment]
Skapa kodverk för HSA-verksamhetskod, knyt organization.type till ett VS för detta
OID för HSA verksamhetskoder: 1.2.752.129.2.2.1.3
Vi avvaktar med de andra kodverken till dess att behov uppstår och någon tar ägandeskap och tar fram en namnrymd för dessa.

**Comment by HL7Sverige** [comment]
@HL7Sverige - Gör detta och dokumentera designvalen i IG

**Comment by HL7Sverige** [comment]
Klart

**Comment by HL7Sverige** [comment]
Reviewed at meeting 4/4
