### ISSUE TITLE
Fastslå identifierare för kodverk för legitimationsyrken samt legitimationskod/identifierare

### ISSUE THREAD

**Issue by danka74** [HL7Sweden/basprofiler-r4#39]
1. 
ValueSet: SEBaseHOSPLegitimationsYrkeVS
* insert SEStandardRuleSet
* include codes from system urn:oid:1.2.752.116.3.1.3

ändra på motsvarande slice i Practitioner.qualification.

2. Det behövs en ny identifierare 
1.2.752.116.3.1.1 behövs som slice på qualification.identifier.

**Comment by danka74** [comment]
Från: Hjärtsjö, Magnus <magnus.hjartsjo@socialstyrelsen.se> 
Skickat: den 4 november 2021 09:28
Till: Karlsson, Daniel <Daniel.Karlsson@socialstyrelsen.se>
Ämne: SV: OID för HOSP yrkeskoder

Hej Daniel,

Vi är ledsna att just ditt mail kommit bort i hosp@socialstyrelsen.se
Vi  på HoSp-funktionen är inte så mycket insatta i OID:er, eftersom vi jobbar direkt mot DHS-HoSp och vår s.k. Totalfil.

Kodverk för yrkeskoder (i dagsläget 23 legitimerade yrken) är inte HOSP-ID (hospid).
hospid är intern DHS-serie för att, i HoSp, identifiera behörighetssökande. hospid är ett löpnummer i DHS som delas med alla andra delar av DHS.

Magnus


Med vänlig hälsning
………………………………..

Magnus Hjärtsjö
Utredare/Programme officer

SOCIALSTYRELSEN
Rättsavdelningen
Förvaltningsjuridik
106 30 Stockholm
Växel 075-247 30 00
www.socialstyrelsen.se

**Comment by danka74** [comment]
Se https://www.sambi.se/wp-content/uploads/2019/05/Sambi_Attributspecifikation_1.5.pdf sid 5

![image](https://user-images.githubusercontent.com/2042998/140933262-53f5eb90-aea2-430e-a6da-cb90738fe24c.png)

**Comment by HL7Sverige** [comment]
Eftersom HoSp-ID inte ska användas som extern identifierare så beskriver vi inte den nu i profilen (@danka74  följer upp med följdfråga till HoSp-förvaltningen) utan enbart användningen av kodverket enligt OID ovan.

**Comment by HL7Sverige** [comment]
Efter lite resonerande backar vi på förra kommentaren och implementerar enligt 1:a kommentaren. Dv.s. 
Skapa ValueSet: SEBaseHOSPLegitimationsYrkeVS från urn:oid:1.2.752.116.3.1.3
Knyt detta VS till slice för qualification.code 

Skapa ValueSet SEBaseHOSPId från 1.2.752.116.3.1.1
Knyt detta VS till slice för qualification.identifier
