### ISSUE TITLE
Design av HumanName avseende mellannamn

### ISSUE THREAD

**Issue by danka74** [HL7Sweden/basprofiler-r4#4]

**Comment by HL7Sverige** [comment]
Se beslutsunderlag och kommentera i detta issue gällade frågan. Röstning avseende lösningsalternativ tas under nästa möte

**Comment by VikJer** [comment]
**Kliniska behovet**
- Okulär besiktning - [Vårdhandboken](https://www.vardhandboken.se/arbetssatt-och-ansvar/ansvar-och-regelverk/identifikation/oversikt/) säger att "Det är viktigt att fastställa varje vårdtagares identitet för att kunna garantera trygghet och säkerhet i alla kontakter med vårdgivare. Den som utför en medicinsk åtgärd är skyldig att varje gång förvissa sig om vårdtagarens identitet. **Kontrollen ska ske mot en godkänd legitimationshandling**, att personens identitet inte går att fastställa innebär inte att patienten kan nekas nödvändig vård.". Det pekar på att namnet har en betydligt svagare roll i själva identitetsfastställandet än man kan få bilden av i introduktionstexten. Namn utan personidentitet är ett sällsynt fenomen för vården att hantera, och när patienter väl är registrerade inom vården så tilldelas de en identitet (om de inte redan har en) vilket gör att namnets betydelse i det avseendet är litet. I de fall patienter inte behöver ange sin identitet den för att motta vård faller hela behovet av identifiering bort, då vården har andra rutiner för att bedriva den typen av verksamhet. 

- Kunna ge ett personligt bemötande genom att veta korrekt namn - Förvisso viktigt, men det görs knappast via mellannamn, och det är inte heller verksamhetskritiskt på samma nivå som förväxlad identitet är.

**Situationer**
- Utbyte av svensk patientinformation i en svensk kontext - Det är oklart vad som avses när man säger att vi ska ta fram en basprofil som vi inte kan räkna med att alla kan följa. Med det resonemanget spelar ju heller inte innehållet i basprofilen någon roll? Själva grunden **MÅSTE** vara att profiler används som **kontrakt** mellan två parter som ska integrera sina system med varandra, och att FHIRs funktionalitet för validering av resurser mot profiler och implementationsguider är de som används.
- Utbyte av svensk patientinformation i en internationell kontext - Användningsfallet är irrelevant för scopet av vår basprofil. Profilerna vi tar fram måste vara kopplade till användningsfall och inte vara API-specifikationer. FHIR-standarden själv erkänner och beskriver den problematik som systemleverantörer ställs inför vid användandet av FHIR i olika situationer:

> Note that because of the nature of the healthcare ecosystem, there may be multiple overlapping sets of adaptations - by healthcare domain, by country, by institution, and/or by vendor/implementation. [Källa](http://hl7.org/fhir/profiling.html#5.1.0)

FHIR pratar om [två typer av profiler](http://hl7.org/fhir/profiling.html#profile-uses):
- Profiler som beskrivning av ett APIs förmåga att hantera information [Källa](http://hl7.org/fhir/profiling.html#CapabilityStatement.rest.resource.profile)
- Profiler som beskrivning av information som hanteras av ett system kopplat till ett användningsfall [Källa](http://hl7.org/fhir/profiling.html#CapabilityStatement.rest.resource.supportedProfile)

Motiveringen till förslagen med redundans och "hängslen och livremmar" vilar i min mening sig till stor del på antagandet att det är den första typen av profiler vi jobbar med. I det perspektivet är resonemangen fullt begripliga. För mig personligen står det dock klart att det snarare är den andra typen av profilering som vi arbetar med i den här arbetsgruppen.

Underlaget saknar också information om att samtliga nordiska länder där man har behovet av att uttrycka mellannamn, där definitionen av mellannamn också skiljer sig från den anglosaxiska, har valt att gå samman och välja lösningen med en nordiskt gemensam extension.

**Comment by MajaHedengren** [comment]
[Exempel API som hanterar svenska namn enligt förslag på nationell profil.docx](https://github.com/HL7Sweden/basprofiler-r4/files/4297938/Exempel.API.som.hanterar.svenska.namn.enligt.forslag.pa.nationell.profil.docx)

Katrin och Emmelis jobb angående hur hanteringen av mellannamn ska ske.

**Comment by HL7Sverige** [comment]
Beslut att gå vidare med alternativ 2.3 och utforma extensions för detta.

**Comment by HL7Sverige** [comment]
Extensions och profil klar i forkat repository - demo 17/11 2020
