### ISSUE TITLE
Egen kod för "skyddad folkbokföring"?

### ISSUE THREAD

**Issue by emmeligross** [HL7Sweden/basprofiler-r4#42]
Det finns tre typer av skyddade personuppgifter, se https://www.skatteverket.se/privat/folkbokforing/skyddadepersonuppgifter.4.18e1b10334ebe8bc80001711.html?q=skyddad+folkbokf%C3%B6ring 
Lösningen för att kommunicera skyddade personuppgifter är att vi anger koder i  meta.security.
Vi har i basprofilen för Patient enbart stöd för att kommunicera "sekretessmarkering" med en egen svensk kod. 
Borde vi ha en kod för "skyddad folkbokföring"? ("fingerade personuppgifter" bör väl inte kommuniceras?)

**Comment by HL7Sverige** [comment]
Beslut om att lägga till denna kod på möte 9/11, se även issue #8 för lösning

**Comment by HL7Sverige** [comment]
Lad till koden skyddadFolkbokforing
