### ISSUE TITLE
Bug in SE base profile for Patient

### ISSUE THREAD

**Issue by vjernelov** [HL7Sweden/basprofiler-r4#50]
The slicing for Patient.identifier:nationelltReservnummer has a fixed value set to **_nationelltReservnumer_**.

The typo should be fixed.

**Comment by danka74** [comment]
Fixed in https://github.com/HL7Sweden/basprofiler-r4/commit/9328f832370293e9587d98e34eef556f3da87db5

**Comment by danka74** [comment]
@peturv Kontrollera vilken version den kommer ut i (eller har kommit ut)

**Comment by danka74** [comment]
Buggen finns i v1.0.0, men inte i master.
