### ISSUE TITLE
Formal build and upload to fhir registry

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#53]
@danka74 or @peturv - I have been struggling with making a correct formal build for the se-base that can be uploaded to the webserver and registered to the fhir-registry following the great instructions you make Petur. There seems to be some issue with linebreaks that I can´t get by head around.

Can one of you give it a try and make a zip of the web structure that I can upload to hl7.se/fhir?

**Comment by peturv** [comment]
I can absolutely help. I'll see if I can take some time tomorrow.

**Comment by peturv** [comment]
I've created a zip with contents, but its just a tad too large to upload here so I added it to the fork of basprofiler in our Chorus project: [Click here to download zip](https://github.com/Chorus-AB/basprofiler-r4/raw/release/1.0.0-with_output/published/hl7se_base_profiles_1-0-0.zip)

Adding a pull-request for the release branch I created as well. I used the previous point in time we had been working at as branching point.

**Comment by peturv** [comment]
We might want to tag that point in time as 1.0.0 as well, depending on if we want to utilize release branches or tags.

**Comment by HL7Sverige** [comment]
@peturv - great work, thank you. I uploaded the result to hl7.se and noticed that the official url:s that are generated omits the version number. See for example http://hl7.se/fhir/ig/base/1.0.0/StructureDefinition-SEBasePatient.html that should possible to refer with http://hl7.se/fhir/ig/base/1.0.0/StructureDefinition/SEBasePatient, but the URL generated in the profile is http://hl7.se/fhir/ig/base/StructureDefinition/SEBasePatient

**Comment by peturv** [comment]
> @peturv - great work, thank you. I uploaded the result to hl7.se and noticed that the official url:s that are generated omits the version number. See for example http://hl7.se/fhir/ig/base/1.0.0/StructureDefinition-SEBasePatient.html that should possible to refer with http://hl7.se/fhir/ig/base/1.0.0/StructureDefinition/SEBasePatient, but the URL generated in the profile is http://hl7.se/fhir/ig/base/StructureDefinition/SEBasePatient

I wrote a bit about this on : https://github.com/SvenskaIndustriProfiler/fhir/issues/26#issue-1282565912

Basically this behavior is correct since different versions of the profile should share a canonical url. We should probably add a redirect that both resolves canonical urls to the correct html pages and to the “current” version.

**Comment by peturv** [comment]
I’m working on a small wordpress plugin to handle this, but setting up the behavior on either apache with mod_rewrite or nginx, depending on what you are running the site on.

**Comment by HL7Sverige** [comment]
Ok, I have fixed the redirections. Tagging the release now
