### ISSUE TITLE
Integrera github mot build.fhir.org för publicering av profiler

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#7]
Även beslut att gå över till shorthand istället för Forge
Publicera även på Simplifier via github integration

**Comment by danka74** [comment]
Intruktioner finns här: https://github.com/FHIR/auto-ig-builder

**Comment by danka74** [comment]
Klart, se här: http://build.fhir.org/ig/danka74/basprofiler-r4/
