### ISSUE TITLE
Bedömning av lösningar för hantering av sekretessmarkering

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#8]
De beslutsdokument. 
Viktor och Martin har haft en diskussion om lämpligt lösningsalternativ med Graham och dom behöver dokumentera resultatet av denna diskussion.

**Comment by HL7Sverige** [comment]
Katrin och Viktor tar tag i detta och kommer med förslag nästa möte

**Comment by VikJer** [comment]
[Beslutsmatris Sekretessflagga.docx](https://github.com/HL7Sweden/basprofiler-r4/files/5689347/Beslutsmatris.Sekretessflagga.docx)

Utredningen kring sekretessmarkering bifogas i ärendet. Om man inte deltog i arbetet är det svårt att kunna ta ställning till hur färgkodningen av de olika utfallen gått till då det saknas resonemang i texten, och således svårt att värdera om man kan ställa sig bakom resultatet.

Då både Grahame Grieve och FHIR-standarden själv pekar på alternativ 2 som den man bör använda (källa: https://chat.fhir.org/#narrow/stream/194447-nordics/topic/Secrecy.20on.20Patient.20data) ställer åtminstone jag (Viktor) mig frågande till resultatet av utredningen.

Nästa steg bör vara att vi landar i **hur** vi går vidare med frågan. Ska vi godta förslaget trots frågetecknen eller ska vi omarbeta förslaget? I förlängningen kan det även vara värt att fundera över om modellen med beslutsmatrisen behöver förfinas något för att den ska kunna ge den önskade effekten.

**Comment by VikJer** [comment]
Vi utgår från Grahames förslag, att vi ska inkludera BÅDE DEMO för bredare interoperabilitet, SAMT en egen kod för att representera vårt svenska lagrum (Skatteverkets sekretessmarkering) som ligger till grund för flaggan (dvs en "logisk alternativ 2").

Arbetet bör tas vidare genom att förslag tas fram för att beskriva alternativ till hur detta kan implementeras i profilen.
Vi behöver ta fram förslag på hur den svenska koden ska benämnas.

**Comment by HL7Sverige** [comment]
Tobias, Daniel och Arvid tar en sittning innan nästa möte och tar fram förslaget

**Comment by danka74** [comment]
Möte Tobias, Daniel 2021-01-20
Sekretessmarkering kan behöva användas för Patient-, Person-, Practitioner-resurserna. (också PractitionerRole, RelatedPerson, Group? Skatteverkets markering är kopplad till person, så troligtvis inte).
Vi tolkar tidigare diskussioner som att vi inte skiljer på olika nivåer av sekretessmarkering. Sekretessmarkering och skyddad folkbokföring hanteras likadant i profilerna.
Ändringar genomförda på github http://build.fhir.org/ig/HL7Sweden/basprofiler-r4/Patient-PatientExample1.html

**Comment by danka74** [comment]
Referens till lag/föreskrift som reglerar sekretessmarkering

**Comment by HL7Sverige** [comment]
Lägg till en designation "sekretessmarkering" och stäng ärendet

**Comment by HL7Sverige** [comment]
Verkar inte går att lägga till designation på något smidigt sätt med FSH. Får kanske nöja oss med textuell referens till lagrum

**Comment by HL7Sverige** [comment]
klart
