### ISSUE TITLE
Improve the coverage of the example Patient resources

### ISSUE THREAD

**Issue by vjernelov** [HL7Sweden/basprofiler-r4#80]
**20 maj**
VGRs PU-datafolk hänvisade till Ineras testmiljö för PU-tjänsten. @joakim-berg fick ett utdrag med ett antal exempel som vi kan utgå från. Han efterfrågade ett antal kompletterande uppgifter (samordningsnummer med styrkt identitet, sekretessmarkerad person, skyddad folkbokföring).

Testdatat läggs upp i ärendet som bilaga (XML-fil).

----------------------------------------------------------------------------------------------------------------------------------------------------

@joakim-berg kollar med VGR om han kan skaka fram testpatientdata som används i regionen. @larbo4 och @tineri1 tittar också internt på Inera och ser vad som kan vaskas fram. Ambitionen är att återanvända det arbetet och direktöverföra det till våra testpatientresurser. Vi kommer även vilja inkludera personidentifierare för de olika identifierartyperna i några av fallen som vi väljer ut.

**Comment by joakim-berg** [comment]
Test data for patients fetched from Inera PU test environment.

Two files provided in zip archive.
**PersonRecord_response.xml**
196101182803 – folkbokförd län 14 med relationer mm 
189002029800 – folkbokförd län 14 med folkbokföringshistorik (HistoricalRecords) mm
200302022389 – folkbokförd län 14 med invandringsdatum, födelseort i utlandet mm
199002222397 – avregistrerad utvandrad (UV), utlandsadress mm

**PersonRecord_response2.xml**
196109732393 – samordningsnummer
200001252386 – sekretessmarkerad (filtrerad information enligt VGR beslut)
189602029812 – skyddad folkbokföring (filtrerad information enligt VGR beslut)
98240301AA06 - Nationellt reservid
20210325K069 - VGR-formaterat reservnummer



[PersonRecord_response.zip](https://github.com/user-attachments/files/15762614/PersonRecord_response.zip)

**Comment by vjernelov** [comment]
@joakim-berg jobbar vidare med att uppdatera exemplen så att de baseras på basprofilen och innehåller de data som ska ingå i resursen. Vi lägger exemplen i en separat .fsh-fil.

Vi kan lägga ett nytt ärende med förslag på hur Github-projektet kan organiseras i enlighet med https://github.com/commonprofiles-care/fhir/issues/100 framtaget inom Commonprofiles-gruppen.
