### ISSUE TITLE
conceptMap FHIR Marital Status - SKV civilstånd?

### ISSUE THREAD

**Issue by annarossander** [HL7Sweden/basprofiler-r4#88]
utred om det ska göras en conceptMap och varför och mellan vilka kodverk. och gör det sen.

**Comment by annarossander** [comment]
om en börjar från början - vad är behovet inom HoS för denna information överhuvudtaget?
Kan vi antingen sedan för den informationen göra ett ändemålsenligt kodverk på patientprofilen? Eller (tipstack @joakim-berg) lägga den informationen på relatedPerson som de gjort i Norge 
https://simplifier.net/hl7norwayno-basis/nobasisrelatedperson

**Comment by joakim-berg** [comment]
Instämmer i förslaget att först utreda informationsbehovet inom HoS. Så gör vi verklig nytta.

VGR avser f n att inte lagra civilstånd i vårt nya VIS, vilket väl ger en fingervisning.

**Comment by annarossander** [comment]
VGR har funderat lite och föreslår att vi inte gör något med detta kodverk (varken mappar eller lägg till NULL #85) och tar bort elementet maritalStatus från den svenska profilen. Ärendet stängs.
