### ISSUE TITLE
Tilltalsnamn hanteras inte? Dubbelnamn ("Knut-Christer")?

### ISSUE THREAD

**Issue by danka74** [HL7Sweden/basprofiler-r4#9]
given är en samling strängar där ordningen är signifikant. Finns idag inget sätt att ange vilket namn som är tilltalsnamn, inte alltid det första. Förtydligande om hur dubbelnamn representeras behövs också.

https://informationsstruktur.socialstyrelsen.se/ModelViewer?page=ClassDiagram_hloUpWKFYEBgdAUY.html

"Angivelse av tilltalsnamnsmarkering, som används för att markera vilket av de angivna förnamnen som är personens tilltalsnamn. Giltiga värden är 10-99 där den första siffran anger vilket av de angivna förnamnen som är tilltalsnamnet (1 motsvarar första namnet osv.) och den andra siffran anger det eventuella andra tilltalsnamnet om dubbelnamn är aktuellt. Om inte är den andra siffran 0"

**Comment by danka74** [comment]
Specifikation: ISO/TS 22220:2008 Health informatics — Identification of subjects of health care

https://share.ansi.org/shared%20documents/Standards%20Activities/Healthcare%20Informatics%20Technology%20Standards%20Panel/Standardization%20Committees/Foundations/Foundations%20Harmonization/ISO_TS_22220_20071219%20images.pdf

**Comment by danka74** [comment]
Arketyp för personnamn: https://ckm.openehr.org/ckm/archetypes/1013.1.477

**Comment by HL7Sverige** [comment]
Bör man inte kunna arbetar med orderMeaning?
https://www.hl7.org/fhir/elementdefinition-definitions.html#ElementDefinition.orderMeaning

**Comment by tobiasblom** [comment]
Om jag förstår det rättskulle det då gå till på följande vis: 

Jag heter Birgitta Anne Marie Svensson. Anne Marie är ett mitt tilltalsnamn och ett dubbelnamn utan bindestreck. Man skulle du använda orderMeaning för att flagga "true" och sedan i en sträng beskriva att Anne Marie är mitt tilltalsnamn? 
Om jag har förstått det rätt, hur visas detta upp i ett journalsystem? Måste en sjuksköterska då läsa strängen för att få veta att mitt tilltalsnamn är Anne Marie? I så fall låter det en aning krångligt.

Här är alternativ jag funderat på:

1. Använda en preferred extension och flagga varje förnamn som antingen preferred eller inte. Däremot vet jag inte hur man löser ordningsföljden på eventuella dubbelnamn. Finns det risk att man tror att jag heter Marie Anne istället?
https://www.hl7.org/fhir/extension-iso21090-preferred.html

2. Använda en EN-qualifyer extension. Då kan förnamn och prefix markeras enligt ett kodverk. Även här undrar jag om följden av namnen kan påverkas?
https://www.hl7.org/fhir/extension-iso21090-en-qualifier.html

3. Definiera en ny extension baserad på Socialstyrelsens NI och tilltalsnamnsmarkering som Daniel nämner ovanför.

**Comment by HL7Sverige** [comment]
Emmeli tittar på hur man har löst detta i NLL - det med flera tilltalsnamn som olika namn

**Comment by emmeligross** [comment]
Så här beskrivs hanteringen av tilltalsnamn från Navet:
"Om uppgift om tilltalsnamn finns för förnamn markeras detta med en numerisk tvåställig kod enligt följande exempel:
Eva Mia: Mia är tilltalsnamnet, markeras med 20.
Kjell Olof: Kjell Olof är tilltalsnamn, markeras med 12.
Hedvig Britt-Marie: Britt-Marie är tilltalsnamn, markeras med 23 (förnamn med bindestreck betraktas som två namn)."

Alla förnamn kommer i en enda sträng. 

När vi på E-hälsomyndigheten tittade i vår kopia av Folkbokföringen kunde vi se att namnkoden (den numeriska koden som markerar tilltalsnamn) såg ut på följande sätt:
Namnkod        antal
10                      5122861
null                   2050780
20                      1775154
00                      894557
30                      396572
12                      185335
23                      65611
40                      8493
34                      5651
13                      579
50                      296
45                      138
14                      107
60                      27
24                      26
56                      6
15                      5
19                      3
70                      3
16                      3
80                      2
21                      1
90                      1
67                      1
35                      1

Värt att observera är att det finns en person som har två namn som tilltalsnamn där det första tilltalsnamnet kommer efter det andra tilltalsnamnet (namnkod = 21). Man skulle kunna ifråga sätta om denna namnkod verkligen stämmer.
Det finns också ett stort antal poster där namnkod saknas (null) eller där namnkoden är 00.

I FHIR har HumanName.given kardinaliteten 0..*, och användningen beskrivs avpå följande sätt: "Given Names appear in the correct order for presenting the name"

Det blir då en utmaning att få dessa två modeller att fungera tillsammans. 

I Nationella Läkemedelslistan (NLL) har E-hälsomynidgheten valt att använda utökningen https://www.hl7.org/fhir/extension-iso21090-en-qualifier.html tillsammans med koden "CL" (Call me | Callme is used to indicate which of the various name parts is used when interacting with the person) för att markera det eller de namn som är klassade som tilltalsnamn.
I det fall att en person har ett dubbelnamn med bindestreck kommer NLL att hantera det som ett (1) namn och lägga in det som en (1) post i "given". (Antagande som görs: ett dubbelnamn med bindestreck där det första namnet pekats ut i första siffran i namnkoden så antar vi att namnet efter bindestrecket alltid är det andra namnet i namnkoden)

**Comment by HL7Sverige** [comment]
Vi skapar en utökning enligt eHMs exempel (NLLPatient)
